blog_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

from core import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
] 

urlpatterns += [
    re_path('html/(?P<path>.*)', core_views.serve_html, name='html'),
    # index
    # path('', core_views.index, name='index'),
    path('',
         core_views.post_list_view, {'category': 'all'}, name='post_list'),
    # none category post
    path('category/',
         core_views.post_list_view, name='post_list'), 
    # all or select category
    path('category/<str:category>/',
         core_views.post_list_view, name='post_list'),
    path('post/<int:pk>/', core_views.post_detail_view, name='post_detail'),
    path('post/create/', core_views.post_create_view, name='post_create'),

    # api
    path('api/category/', core_views.get_category_list, name='api_category'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from treebeard.mp_tree import MP_Node
from taggit.managers import TaggableManager

from model_utils.fields import StatusField
from model_utils import Choices

# Create your models here.


class Category(MP_Node):
    STATUS_CHOICES = Choices('public', 'private')
    status = StatusField(choices_name='STATUS_CHOICES')
    name = models.CharField(max_length=80)
    parent = models.ForeignKey('self',
                               related_name='children_set',
                               null=True,
                               db_index=True,
                               on_delete=models.CASCADE)
    sib_order = models.PositiveIntegerField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    node_order_by = ['name']

    def __str__(self):
        return "%s %s" % (self.id, self.name)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Post(models.Model):
    STATUS_CHOICES = Choices('draft', 'published')
    status = StatusField(choices_name='STATUS_CHOICES')
    category = models.ForeignKey(
        Category, blank=True, null=True,  on_delete=models.CASCADE)
    title = models.CharField(max_length=80, blank=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True, blank=True)
    updated = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    tag = TaggableManager(blank=True)

    def __str__(self):
        return "%s %s - %s - %s" % (self.id, self.category, self.title, self.body[:30])

    def save(self, *args, **kwargs):
        if not self.title:
           self.title = self.body[:20]
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

core/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['category', 'title', 'body']
        widgets = {
            'category': forms.Select(attrs={'class': 'uk-select'}),
            'title': forms.TextInput(attrs={'class': 'uk-input'}),
            'body': forms.Textarea(attrs={'class': 'uk-textarea'}),
        }

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import redirect, resolve_url
from .models import Category, Post
import json

from .forms import *

import logging
logger = logging.getLogger('django')
# logger.info('the_file: %s' % the_file)

# # Create your views here.


def serve_html(request, path):
    # logger.info('path: %s' % path)

    return render(request, path)


def index(request, message=None):
    return render(request, 'index.html')



def get_category_list(request):
    data = Category.dump_bulk()
    return HttpResponse(json.dumps(data), content_type='application/json')



def post_list_view(request, category=None):
    if category:
        if category == 'all':
            posts = Post.objects.all().order_by('-updated')[:20]
        else:
            posts = Post.objects.filter(
                category__slug=category).order_by('-updated')[:20]
    else:
        posts = Post.objects.filter(category=None).order_by('-updated')[:20]

    data = {
        'posts': posts
    }
    return render(request, 'post/post_list.html', context=data,)


def post_detail_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    data = {
        'post': post
    }
    return render(request, 'post/post_detail.html', context=data)


def post_create_view(request, category=None):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PostForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            post = form.save()
            return HttpResponseRedirect(resolve_url('post_detail', post.id))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PostForm()

    return render(request, 'post/post_create.html', {'form': form})

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

  <script src="{% static 'js/main.js' %}"></script>
  
</body>
</html>

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}My amazing blog{% endblock %}</title>
    <!-- Include external CSS. -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.40/css/uikit.min.css" />
    <style>
      html {
        position: relative;
        min-height: 100%;
      }
    
      body {        
        margin-bottom: 80px;
      }
    
      #header {
        padding: 1em 0;
        /* line-height: 2.5em; */
        /* height: 50px; */
        /* margin-bottom: 50px; */
        
      }

      header a {
        margin: 1em;
      }
      nav {        
        width: 200px;
        /* background: #faffbf; */
        background: white;
        
      }     


      nav>ul{
        border-right: 1px solid gray;
      }

      footer {
        position: absolute;
        bottom: 0;
        width: 100%;        
        line-height: 60px;
        background-color: white;
        text-align: center;
        font-size: .8em;
        color: gray;
        
      }
    
      /* div, header, nav, main, article {
        outline: mediumpurple 1px solid;
      } */
    </style>
    {% block style %} {% endblock %}
</head>
<body>
  <div id="wrap">

    <!-- start header -->
    <!-- uk-navbar start -->
    <header id="header" class="uk-navbar-container uk-margin" style="margin-bottom: 20px; z-index: 980;" uk-sticky="show-on-up: true; animation: uk-animation-slide-top;" uk-navbar>
      <div class="uk-navbar-left">        
         {% if request.user.is_authenticated %}
        <a href="{% url 'post_create' %}" class="uk-button uk-button-default" uk-toggle>ADD
          <span class="uk-margin-small-right" uk-icon="icon: plus-circle"></span>
        </a>
         {% endif %}
      </div>
      <div class="uk-navbar-center">
        <a class="logo uk-navbar-item uk-logo" href="/">BLOG</a>
      </div>
      <div class="uk-navbar-right">
        <!-- <a href="#offcanvas-slide" class="uk-button uk-button-default uk-hidden@s" uk-toggle>Open</a> -->
        <a href="#offcanvas-slide" class="uk-button uk-button-default uk-hidden@s" uk-toggle>Item <span class="uk-margin-small-right" uk-icon="icon: table"></span></a>
      </div>
    </header>
    <!-- uk-navbar end -->
    <!-- end header -->



    <!-- container start -->
    <div class = "container" uk-grid>
      {% block main %}
      <!-- nav start -->
      <nav class="uk-visible@s">
        <ul uk-sticky="offset:100;">
          <li>
            by simmh
          </li>
          <li class='category'>
            CATEGORY
            <div class="ajax_category"></div>
          </li>
          <li>
            TAGS
          </li>
        </ul>
      </nav>        
      <!-- nav end -->
      
      
      <!-- main start -->
      <main class="uk-width-expand">
        {% block content %}
        <article>
      
        </article>
        {% endblock %}
      
      </main>
      <!-- main end -->
      {% endblock %}
    </div>
    <!-- container end -->
    

    <!-- footer start -->
    <footer class="footer" uk-sticky="bottom: true">
      <div class="uk-text-center">
        <span class="text-muted">Copyright©2018 by simmh</span>       
      </div>
    </footer>
    <!-- end footer -->
  </div>

  <!-- off-menu start -->
  <!-- <div id="off-menu" uk-offcanvas>
    <div class="uk-offcanvas-bar">
      <button class="uk-offcanvas-close" type="button" uk-close></button>
        <ul>
          <li>menu 1</li>
          <li>menu 2</li>
          <li>menu 3</li>
        </ul>
    </div>
  </div> -->

  <div id="offcanvas-slide" uk-offcanvas>
    <div class="uk-offcanvas-bar">  
      <div class="ajax_category"></div>
    </div>
  </div>
  <!-- off-menu end -->


  <!-- Include external JS libs. -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>

    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.40/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.40/js/uikit-icons.min.js"></script>
   

    <script src="{% static '/js/main.js' %}"></script>
    {% block script %} {% endblock%}
</body>
</html>

templates/post/post_create.html
{% extends "layout/base.html" %} 

{% block title %}
POST CREATE
{% endblock %}
{% block style %}
<!-- Include Editor style. -->
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.5/css/froala_editor.min.css' rel='stylesheet' type='text/css'
/>
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.5/css/froala_style.min.css' rel='stylesheet' type='text/css'
/>
<style>
  #id_body {
    min-height: 500px ;
  }
</style>
{% endblock%}
{% block main %}

  <h3 class="uk-card-title">POST CREATE</h3>
  <form action="{% url 'post_create'%}" method="POST" uk-grid>
    {% csrf_token %} 
        <div class="uk-width-1-4">
           {{form.category}}
        </div>
        <div class="uk-width-3-4">
           {{form.title}}
        </div>
        <div class="uk-width-1-1">
           {{form.body}}
        </div>
        <div class="uk-width-1-1">
          <button class="uk-button uk-button-default uk-button-large">Cancel</button>
          <button type="submit" value="Submit" class="uk-button uk-button-primary uk-button-large">Submit</button>
        </div>
      </form>





{% endblock%}

{% block script %}
    <!-- Include Editor JS files. -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.7.5/js/froala_editor.pkgd.min.js"></script>
    
    <!-- Initialize the editor. -->
    <script> 
      $(function () { $('#id_body').froalaEditor({
      }) });
    </script>


{% endblock %}

templates/post/post_detail.html
{% extends "layout/base.html" %}

{% block content %}
<article class="uk-article">
  <h1 class="uk-article-title">
    {{post.title}}
  </h1>
  <p class="uk-article-meta">
     Written by Super User on {{post.updated|date:'Y.m.d H:i'}}. 
     Posted in <a href="{% url 'post_list' post.category.name %}"> {{post.category.name}} </a>
  </p>
  <p class="uk-text-lead"></p>
  
    {{post.body|safe}}
    <!-- <div class="uk-grid-small uk-child-width-auto" uk-grid>
      <div>
        <a class="uk-button uk-button-text" href="#">Read more</a>
      </div>
      <div>
        <a class="uk-button uk-button-text" href="#">5 Comments</a>
      </div>
    </div> -->
</article>
{% endblock%}

templates/post/post_list.html
{% extends "layout/base.html" %} 
{% block style %}
<style>
.post-list {

}

.post-list span.title {
  color: #181818;
}

.post-list span.date {
  color: lightslategrey;
  font-size: .8em;
}
</style>
{% endblock %}
{% block content %}

<ul class="post-list">
{% for p in posts %}
  <li>
    <a href="{% url 'post_detail' p.id %}">
    <span class="title">{{p.title}}</span> 
    <span class="date">{{p.updated|date:'Y.m.d H:i'}}</span>
  </a>
</li>
{% endfor %}
</ul>
{% endblock%}